services:
  mongo:
    image: mongo:6.0
    container_name: solia-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    container_name: solia-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/solia
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo


volumes:
  mongo-data:
